### ISSUE TITLE
Sling 1.2.3.post1 is broken on arm64 macs

### ISSUE THREAD

**Issue by cmpadden** [slingdata-io/sling-python#18]
On version `1.2.2` I had no issues, however, the latest version appears to have some dependency resolution errors on m-series macbooks in that it is looking for `sling­_mac­_amd64` instead of `sling­_mac­_arm64`.

```
$ pip freeze | grep sling
sling==1.2.3.post1
sling-mac-arm64==1.2.3.post1
```

```
3.11/lib/python3.11/site-packages/sling/­_­_init­_­_.py", line 41, in <module>
    exec('from sling­_mac­_amd64 import SLING­_BIN')
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sling­_mac­_amd64'
```

**Comment by flarco** [comment]
Interesting. What command did you run? `pip install sling` or `pip install -U sling`?

**Comment by cmpadden** [comment]
This was with `pip install sling`.
```
$ pip install sling
Resolved 2 packages in 54ms
Installed 2 packages in 5ms
 + sling==1.2.3.post1
 + sling-mac-arm64==1.2.3.post1
```

```
$ python
Python 3.11.7 (main, Jan 26 2024, 16:20:21) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sling
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/colton/src/playground/test/.direnv/python-3.11/lib/python3.11/site-packages/sling/__init__.py", line 41, in <module>
    exec('from sling_mac_amd64 import SLING_BIN')
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sling_mac_amd64'
```

**Comment by cmpadden** [comment]
@flarco confirmed we're good to go, thanks for the unbelievably fast turnaround!

```
$ pip install sling
Resolved 2 packages in 1.76s
   Built sling-mac-arm64==1.2.3.post2
   Built sling==1.2.3.post2                                                                                                     Downloaded 2 packages in 4.20s
Installed 2 packages in 1ms
 + sling==1.2.3.post2
 - sling-mac-arm64==1.2.3.post1
 + sling-mac-arm64==1.2.3.post2

$ python
Python 3.11.7 (main, Jan 26 2024, 16:20:21) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sling
>>>
```
